// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Polyclinic.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Patients",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PassportNumber = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    FullName = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    BirthDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Address = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    BloodGroup = table.Column<int>(type: "int", nullable: false),
                    RhFactor = table.Column<int>(type: "int", nullable: false),
                    PhoneNumber = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Patients", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Specializations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    Code = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Specializations", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Doctors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PassportNumber = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    FullName = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    BirthDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    SpecializationId = table.Column<int>(type: "int", nullable: false),
                    ExperienceYears = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Doctors", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Doctors_Specializations_SpecializationId",
                        column: x => x.SpecializationId,
                        principalTable: "Specializations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Appointments",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AppointmentDateTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    RoomNumber = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    IsRepeat = table.Column<bool>(type: "bit", nullable: false),
                    PatientId = table.Column<int>(type: "int", nullable: false),
                    DoctorId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Appointments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Appointments_Doctors_DoctorId",
                        column: x => x.DoctorId,
                        principalTable: "Doctors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Appointments_Patients_PatientId",
                        column: x => x.PatientId,
                        principalTable: "Patients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Patients",
                columns: new[] { "Id", "Address", "BirthDate", "BloodGroup", "FullName", "Gender", "PassportNumber", "PhoneNumber", "RhFactor" },
                values: new object[,]
                {
                    { 1, "ул. Ленина, д. 10, кв. 25", new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 1, "Смирнов Алексей Викторович", 1, "6001 123456", "+7 (999) 123-45-67", 0 },
                    { 2, "ул. Гагарина, д. 5, кв. 12", new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), 0, "Кузнецова Елена Дмитриевна", 2, "6002 234567", "+7 (999) 234-56-78", 0 },
                    { 3, "пр. Мира, д. 15, кв. 7", new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 2, "Попов Сергей Иванович", 1, "6003 345678", "+7 (999) 345-67-89", 1 },
                    { 4, "ул. Советская, д. 8, кв. 42", new DateTime(1995, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 3, "Васильева Мария Петровна", 2, "6004 456789", "+7 (999) 456-78-90", 0 },
                    { 5, "ул. Пушкина, д. 3, кв. 56", new DateTime(1982, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), 1, "Соколов Андрей Николаевич", 1, "6005 567890", "+7 (999) 567-89-01", 1 },
                    { 6, "пр. Ленинградский, д. 22, кв. 15", new DateTime(1975, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), 0, "Михайлова Анна Сергеевна", 2, "6006 678901", "+7 (999) 678-90-12", 0 },
                    { 7, "ул. Кирова, д. 12, кв. 8", new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), 2, "Новиков Денис Александрович", 1, "6007 789012", "+7 (999) 789-01-23", 0 },
                    { 8, "ул. Садовая, д. 7, кв. 31", new DateTime(1992, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 3, "Морозова Татьяна Владимировна", 2, "6008 890123", "+7 (999) 890-12-34", 1 },
                    { 9, "пр. Невский, д. 45, кв. 19", new DateTime(1970, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), 1, "Зайцев Игорь Павлович", 1, "6009 901234", "+7 (999) 901-23-45", 0 },
                    { 10, "ул. Комсомольская, д. 6, кв. 23", new DateTime(1965, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 0, "Волкова Ольга Игоревна", 2, "6010 012345", "+7 (999) 012-34-56", 0 },
                    { 11, "ул. Мичурина, д. 18, кв. 67", new DateTime(1998, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), 2, "Белова Наталья Сергеевна", 2, "6011 123456", "+7 (999) 123-56-78", 0 },
                    { 12, "ул. Лермонтова, д. 9, кв. 14", new DateTime(1983, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), 3, "Карпов Евгений Владимирович", 1, "6012 234567", "+7 (999) 234-67-89", 1 }
                });

            migrationBuilder.InsertData(
                table: "Specializations",
                columns: new[] { "Id", "Code", "Description", "Name" },
                values: new object[,]
                {
                    { 1, "THERAPIST", "Врач общей практики", "Терапевт" },
                    { 2, "SURGEON", "Проведение операций", "Хирург" },
                    { 3, "CARDIOLOGIST", "Заболевания сердца", "Кардиолог" },
                    { 4, "NEUROLOGIST", "Заболевания нервной системы", "Невролог" },
                    { 5, "PEDIATRICIAN", "Детские болезни", "Педиатр" },
                    { 6, "GYNECOLOGIST", "Женское здоровье", "Гинеколог" },
                    { 7, "OPHTHALMOLOGIST", "Заболевания глаз", "Офтальмолог" },
                    { 8, "ENT", "Ухо, горло, нос", "Отоларинголог" },
                    { 9, "DERMATOLOGIST", "Кожные заболевания", "Дерматолог" },
                    { 10, "ENDOCRINOLOGIST", "Гормональные нарушения", "Эндокринолог" }
                });

            migrationBuilder.InsertData(
                table: "Doctors",
                columns: new[] { "Id", "BirthDate", "ExperienceYears", "FullName", "PassportNumber", "SpecializationId" },
                values: new object[,]
                {
                    { 1, new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 15, "Иванов Иван Иванович", "4501 123456", 1 },
                    { 2, new DateTime(1975, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), 20, "Петров Петр Петрович", "4502 234567", 2 },
                    { 3, new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 12, "Сидорова Анна Сергеевна", "4503 345678", 3 },
                    { 4, new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 8, "Козлов Дмитрий Николаевич", "4504 456789", 4 },
                    { 5, new DateTime(1982, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), 14, "Морозова Елена Владимировна", "4505 567890", 5 },
                    { 6, new DateTime(1978, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), 18, "Волков Андрей Игоревич", "4506 678901", 6 },
                    { 7, new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), 10, "Соколова Татьяна Александровна", "4507 789012", 7 },
                    { 8, new DateTime(1992, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 6, "Лебедев Михаил Сергеевич", "4508 890123", 8 },
                    { 9, new DateTime(1983, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), 13, "Николаева Ольга Викторовна", "4509 901234", 9 },
                    { 10, new DateTime(1970, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 25, "Федоров Алексей Павлович", "4510 012345", 10 }
                });

            migrationBuilder.InsertData(
                table: "Appointments",
                columns: new[] { "Id", "AppointmentDateTime", "DoctorId", "IsRepeat", "PatientId", "RoomNumber" },
                values: new object[,]
                {
                    { 1, new DateTime(2026, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified), 1, false, 1, "101" },
                    { 2, new DateTime(2026, 2, 5, 11, 0, 0, 0, DateTimeKind.Unspecified), 1, true, 2, "101" },
                    { 3, new DateTime(2026, 2, 10, 14, 30, 0, 0, DateTimeKind.Unspecified), 2, false, 3, "202" },
                    { 4, new DateTime(2026, 2, 15, 9, 15, 0, 0, DateTimeKind.Unspecified), 3, false, 4, "303" },
                    { 5, new DateTime(2026, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified), 1, false, 8, "101" },
                    { 6, new DateTime(2026, 2, 16, 9, 30, 0, 0, DateTimeKind.Unspecified), 1, false, 11, "101" },
                    { 7, new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), 2, true, 6, "101" },
                    { 8, new DateTime(2026, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified), 2, true, 7, "202" },
                    { 9, new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), 3, false, 8, "303" },
                    { 10, new DateTime(2026, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), 2, false, 5, "102" },
                    { 11, new DateTime(2026, 2, 22, 11, 30, 0, 0, DateTimeKind.Unspecified), 6, false, 5, "606" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_DoctorId",
                table: "Appointments",
                column: "DoctorId");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_PatientId",
                table: "Appointments",
                column: "PatientId");

            migrationBuilder.CreateIndex(
                name: "IX_Doctors_SpecializationId",
                table: "Doctors",
                column: "SpecializationId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Appointments");

            migrationBuilder.DropTable(
                name: "Doctors");

            migrationBuilder.DropTable(
                name: "Patients");

            migrationBuilder.DropTable(
                name: "Specializations");
        }
    }
}
