// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polyclinic.Infrastructure.EfCore;

#nullable disable

namespace Polyclinic.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(PolyclinicDbContext))]
    partial class PolyclinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Polyclinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDateTime = new DateTime(2026, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsRepeat = false,
                            PatientId = 1,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDateTime = new DateTime(2026, 2, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsRepeat = true,
                            PatientId = 2,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDateTime = new DateTime(2026, 2, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsRepeat = false,
                            PatientId = 3,
                            RoomNumber = "202"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDateTime = new DateTime(2026, 2, 15, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsRepeat = false,
                            PatientId = 4,
                            RoomNumber = "303"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDateTime = new DateTime(2026, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsRepeat = false,
                            PatientId = 8,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDateTime = new DateTime(2026, 2, 16, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsRepeat = false,
                            PatientId = 11,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDateTime = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsRepeat = true,
                            PatientId = 6,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDateTime = new DateTime(2026, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsRepeat = true,
                            PatientId = 7,
                            RoomNumber = "202"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDateTime = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsRepeat = false,
                            PatientId = 8,
                            RoomNumber = "303"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDateTime = new DateTime(2026, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsRepeat = false,
                            PatientId = 5,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDateTime = new DateTime(2026, 2, 22, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            IsRepeat = false,
                            PatientId = 5,
                            RoomNumber = "606"
                        });
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 15,
                            FullName = "Иванов Иван Иванович",
                            PassportNumber = "4501 123456",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1975, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 20,
                            FullName = "Петров Петр Петрович",
                            PassportNumber = "4502 234567",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 12,
                            FullName = "Сидорова Анна Сергеевна",
                            PassportNumber = "4503 345678",
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 8,
                            FullName = "Козлов Дмитрий Николаевич",
                            PassportNumber = "4504 456789",
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1982, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 14,
                            FullName = "Морозова Елена Владимировна",
                            PassportNumber = "4505 567890",
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1978, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 18,
                            FullName = "Волков Андрей Игоревич",
                            PassportNumber = "4506 678901",
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 10,
                            FullName = "Соколова Татьяна Александровна",
                            PassportNumber = "4507 789012",
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1992, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 6,
                            FullName = "Лебедев Михаил Сергеевич",
                            PassportNumber = "4508 890123",
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1983, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 13,
                            FullName = "Николаева Ольга Викторовна",
                            PassportNumber = "4509 901234",
                            SpecializationId = 9
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1970, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperienceYears = 25,
                            FullName = "Федоров Алексей Павлович",
                            PassportNumber = "4510 012345",
                            SpecializationId = 10
                        });
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Ленина, д. 10, кв. 25",
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 1,
                            FullName = "Смирнов Алексей Викторович",
                            Gender = 1,
                            PassportNumber = "6001 123456",
                            PhoneNumber = "+7 (999) 123-45-67",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Гагарина, д. 5, кв. 12",
                            BirthDate = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 0,
                            FullName = "Кузнецова Елена Дмитриевна",
                            Gender = 2,
                            PassportNumber = "6002 234567",
                            PhoneNumber = "+7 (999) 234-56-78",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "пр. Мира, д. 15, кв. 7",
                            BirthDate = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 2,
                            FullName = "Попов Сергей Иванович",
                            Gender = 1,
                            PassportNumber = "6003 345678",
                            PhoneNumber = "+7 (999) 345-67-89",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Советская, д. 8, кв. 42",
                            BirthDate = new DateTime(1995, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 3,
                            FullName = "Васильева Мария Петровна",
                            Gender = 2,
                            PassportNumber = "6004 456789",
                            PhoneNumber = "+7 (999) 456-78-90",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "ул. Пушкина, д. 3, кв. 56",
                            BirthDate = new DateTime(1982, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 1,
                            FullName = "Соколов Андрей Николаевич",
                            Gender = 1,
                            PassportNumber = "6005 567890",
                            PhoneNumber = "+7 (999) 567-89-01",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "пр. Ленинградский, д. 22, кв. 15",
                            BirthDate = new DateTime(1975, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 0,
                            FullName = "Михайлова Анна Сергеевна",
                            Gender = 2,
                            PassportNumber = "6006 678901",
                            PhoneNumber = "+7 (999) 678-90-12",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "ул. Кирова, д. 12, кв. 8",
                            BirthDate = new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 2,
                            FullName = "Новиков Денис Александрович",
                            Gender = 1,
                            PassportNumber = "6007 789012",
                            PhoneNumber = "+7 (999) 789-01-23",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "ул. Садовая, д. 7, кв. 31",
                            BirthDate = new DateTime(1992, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 3,
                            FullName = "Морозова Татьяна Владимировна",
                            Gender = 2,
                            PassportNumber = "6008 890123",
                            PhoneNumber = "+7 (999) 890-12-34",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "пр. Невский, д. 45, кв. 19",
                            BirthDate = new DateTime(1970, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 1,
                            FullName = "Зайцев Игорь Павлович",
                            Gender = 1,
                            PassportNumber = "6009 901234",
                            PhoneNumber = "+7 (999) 901-23-45",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 10,
                            Address = "ул. Комсомольская, д. 6, кв. 23",
                            BirthDate = new DateTime(1965, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 0,
                            FullName = "Волкова Ольга Игоревна",
                            Gender = 2,
                            PassportNumber = "6010 012345",
                            PhoneNumber = "+7 (999) 012-34-56",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 11,
                            Address = "ул. Мичурина, д. 18, кв. 67",
                            BirthDate = new DateTime(1998, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 2,
                            FullName = "Белова Наталья Сергеевна",
                            Gender = 2,
                            PassportNumber = "6011 123456",
                            PhoneNumber = "+7 (999) 123-56-78",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 12,
                            Address = "ул. Лермонтова, д. 9, кв. 14",
                            BirthDate = new DateTime(1983, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodGroup = 3,
                            FullName = "Карпов Евгений Владимирович",
                            Gender = 1,
                            PassportNumber = "6012 234567",
                            PhoneNumber = "+7 (999) 234-67-89",
                            RhFactor = 1
                        });
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "THERAPIST",
                            Description = "Врач общей практики",
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SURGEON",
                            Description = "Проведение операций",
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CARDIOLOGIST",
                            Description = "Заболевания сердца",
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = 4,
                            Code = "NEUROLOGIST",
                            Description = "Заболевания нервной системы",
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PEDIATRICIAN",
                            Description = "Детские болезни",
                            Name = "Педиатр"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GYNECOLOGIST",
                            Description = "Женское здоровье",
                            Name = "Гинеколог"
                        },
                        new
                        {
                            Id = 7,
                            Code = "OPHTHALMOLOGIST",
                            Description = "Заболевания глаз",
                            Name = "Офтальмолог"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ENT",
                            Description = "Ухо, горло, нос",
                            Name = "Отоларинголог"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DERMATOLOGIST",
                            Description = "Кожные заболевания",
                            Name = "Дерматолог"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ENDOCRINOLOGIST",
                            Description = "Гормональные нарушения",
                            Name = "Эндокринолог"
                        });
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Polyclinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Polyclinic.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Polyclinic.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Polyclinic.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
